<!DOCTYPE html>
<html>
<head>
    <title>{{ $player->user->name }} - Profile</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; }
        .header { text-align: center; border-bottom: 2px solid #00FF41; padding-bottom: 20px; }
        .name { font-size: 30px; font-weight: bold; text-transform: uppercase; margin-bottom: 5px; }
        .role { color: #00FF41; font-weight: bold; font-size: 18px; }
        .section-title { background: #f4f4f4; padding: 10px; font-weight: bold; text-transform: uppercase; margin-top: 30px; border-left: 5px solid #00FF41; }
        .stats-table { width: 100%; margin-top: 10px; border-collapse: collapse; }
        .stats-table td { padding: 10px; border-bottom: 1px solid #eee; }
        .stat-label { font-weight: bold; text-transform: uppercase; font-size: 12px; color: #666; }
        .stat-value { font-weight: bold; text-align: right; color: #00FF41; }
        .footer { margin-top: 50px; text-align: center; font-size: 10px; color: #999; }
    </style>
</head>
<body>
    <div class="header">
        <div class="name">{{ $player->user->name }}</div>
        <div class="role">{{ $player->position }} | U{{ ceil($player->age / 2) * 2 }} Category</div>
    </div>

    <div class="section-title">Personal Details</div>
    <table class="stats-table">
        <tr>
            <td class="stat-label">Age</td>
            <td class="stat-value">{{ $player->age }} Years</td>
        </tr>
        <tr>
            <td class="stat-label">Preferred Foot</td>
            <td class="stat-value">{{ $player->preferred_foot }}</td>
        </tr>
        <tr>
            <td class="stat-label">Height / Weight</td>
            <td class="stat-value">{{ $player->height ?: 'N/A' }} / {{ $player->weight ?: 'N/A' }}</td>
        </tr>
    </table>

    <div class="section-title">Performance Metrics</div>
    <table class="stats-table">
        @foreach($stats as $label => $value)
        <tr>
            <td class="stat-label">{{ $label }}</td>
            <td class="stat-value">{{ $value }}%</td>
        </tr>
        @endforeach
    </table>

    <div class="section-title">Biography</div>
    <p style="font-size: 14px; line-height: 1.6; color: #555;">
        {{ $player->bio ?: 'No biography details provided.' }}
    </p>

    <div class="footer">
        Generated by THINK RIGHT FOOTBALL ACADEMY Management System &copy; {{ date('Y') }}
    </div>
</body>
</html>
